import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Thanachot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <img src="profile.jpg"
          alt="..." className={styles.profile} />
        <h1 className={styles.title}>
          Thanachot Wongmetin
        </h1>
        <p className={styles.description}>
          <code className={styles.code}>Software Engineer · UX/UI Design · Photographer </code>
        </p>
        <Link href="/projects" className={styles.btn}> Start &rarr; </Link>

      </main>
    </>
  )
}
