import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useMediaQuery } from './useMediaQuery.js'
import { Card, Grid, Text, Link, Button, Container, Row, Col, Spacer } from "@nextui-org/react";

const Card4 = () => (
  <Card css={{ p: "$6", mw: "400px" }}>
    <Card.Header>
      <img
        alt="nextui logo"
        src="https://avatars.githubusercontent.com/u/86160567?s=200&v=4"
        width="55px"
        height="55px"
      />
      <Grid.Container css={{ pl: "$6" }}>
        <Grid xs={12}>
          <Text h4 css={{ lineHeight: "$xs" }}>
            Name of Project
          </Text>
        </Grid>
        <Grid xs={12}>
          <Text css={{ color: "$accents8" }}> Type of Project</Text>
        </Grid>
      </Grid.Container>
    </Card.Header>
    <Card.Body css={{ py: "$2" }}>
      <Text>
        Make beautiful websites regardless of your design experience.
      </Text>
    </Card.Body>
    <Card.Footer>
      <Link

        color="primary"
        target="_blank"
        href="https://github.com/nextui-org/nextui"
      >
        Read More
      </Link>
    </Card.Footer>
  </Card>
);
const MockItem = ({ text }: any) => {
  return (
    <img
      alt="nextui logo"
      src="https://avatars.githubusercontent.com/u/86160567?s=200&v=4"
      width="100%"
      height="100%"
    />
  );
};
function App() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/thanachot.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className={styles.title}>Skills & Experience</h1>
          <br />
          <p className={styles.introduce2}>Since beginning my journey as a freelance developer nearly 10 years ago, I’ve done remote work for agencies, consulted for startups, and collaborated with talented people to create web products for both business and consumer use.
            Since beginning my journey as a freelance developer nearly 10 years ago, I’ve done remote work for agencies, consulted for startups, and collaborated with talented people to create web products for both business and consumer use.</p>
          <Link href="resume.pdf" ><Button className={styles.btn2}> <i className="bi bi-file-earmark-pdf-fill" /> &nbsp;  Resume</Button></Link>
        </div>
        <Link href="/" ><Button className={styles.btn2}> &larr;  Back</Button></Link>
        <div className={styles.grid}>
          <Card4 />
          <Card4 />
          <Card4 />
        </div>
      </main>

    </div>


  );
}

function Home() {
  const isMd = useMediaQuery(960);
  const isSm = useMediaQuery(400);
  return (
    <div className={styles.container}>
      <Head>
        <title>My Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/thanachot.ico" />
      </Head>
      <main className={styles.main}>
        <Container gap={0}>
          <Row gap={1} style={{ justifyContent: 'center' }}>
            <div className={styles.description}>
              <h1 className={styles.title}>Skills & Experience</h1>
              <br />
              <p className={styles.introduce2}>Since beginning my journey as a freelance developer nearly 10 years ago, I’ve done remote work for agencies, consulted for startups, and collaborated with talented people to create web products for both business and consumer use.
                Since beginning my journey as a freelance developer nearly 10 years ago, I’ve done remote work for agencies, consulted for startups, and collaborated with talented people to create web products for both business and consumer use.</p>
              <Link href="resume.pdf" ><Button className={styles.btn2}> <i className="bi bi-file-earmark-pdf-fill" /> &nbsp;  Resume</Button></Link>
              <Link href="/" ><Button className={styles.btn2} > &larr;  Back</Button></Link>
            </div>
          </Row>
          <Row gap={1} style={{ justifyContent: 'center' }}>
            <Grid.Container gap={2} justify="center">
              {isMd ? <><Grid xs={12} >
                <Card4 />
              </Grid>
                <Grid xs={12} >
                  <Card4 />
                </Grid>
                <Grid xs={12} >
                  <Card4 />
                </Grid>
                <Grid xs={12} >
                  <Card4 />
                </Grid></> : <><Grid xs={3} >
                  {isMd ? <MockItem /> : <Card4 />}
                </Grid>
                <Grid xs={3} >
                  {isMd ? <MockItem /> : <Card4 />}
                </Grid>
                <Grid xs={3} >
                  {isMd ? <MockItem /> : <Card4 />}
                </Grid>
                <Grid xs={3} >
                  {isMd ? <MockItem /> : <Card4 />}
                </Grid></>}
            </Grid.Container>
          </Row>

        </Container>
      </main>

    </div>
  )
}

export default Home;